name: build

on: push

jobs:

  lint:
    services:
      postgres:
        image: "postgres:12-alpine"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_phoenix_api_template_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.9.0
          otp-version: 22
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Credo
        run: mix test
      - name: Ensure Formatting
        run: mix format --check-formatted

  test:
    services:
      postgres:
        image: "postgres:12-alpine"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_phoenix_api_template_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.9.0
          otp-version: 22
      - name: Install Dependencies
        run: mix deps.get
      - name: Setup DB
        run: mix ecto.setup
      - name: Run Tests
        run: mix test

  build:
    services:
      postgres:
        image: "postgres:12-alpine"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_phoenix_api_template_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.9.0
          otp-version: 22
      - name: Install Dependencies
        run: mix deps.get
      - name: Build binary
        run: mix release
        env:
          MIX_ENV: prod
