name: build

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.9.0
          otp-version: 22
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Credo
        run: mix test
      - name: Ensure Formatting
        run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.9.0
          otp-version: 22
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.9.0
          otp-version: 22
      - name: Install Dependencies
        run: mix deps.get
      - name: Build binary
        run: mix release
        env:
          MIX_ENV: prod
